AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Hello Word for AWS SAM
Resources:
  helloSam:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: rest-api/hello/get/index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: Hello World
      Environment:
        Variables:
          FIRST_NAME: 'Scott'
      MemorySize: 128
      Timeout: 10
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET